from __future__ import annotations

import math
from pathlib import Path
from typing import Callable


def select_example(
    records: list[dict],
    *,
    early: bool,
    honest: bool,
    classify_fn: Callable[[dict], str],
) -> dict | None:
    """Pick a representative completion for the code comparison figure.

    Parameters
    ----------
    records:
        Flat list of completion records.
    early:
        If *True*, restrict to batch <= 50; otherwise batch >= 900.
    honest:
        If *True*, pick the honest program closest to gap=0;
        otherwise pick the highest-gap exploit.
    classify_fn:
        Maps a record to a taxonomy family ID.
    """
    valid = [r for r in records if r.get("outcome") == "valid" and r.get("code")]
    if early:
        pool = [r for r in valid if r.get("batch", 0) <= 50]
    else:
        pool = [r for r in valid if r.get("batch", 0) >= 900]

    if honest:
        pool = [r for r in pool if classify_fn(r) == "honest"]
        pool = [r for r in pool if not math.isnan(r.get("gap", float("nan")))]
        pool.sort(key=lambda r: abs(r.get("gap", 0)))
    else:
        pool = [r for r in pool if classify_fn(r) not in ("honest", "invalid")]
        pool = [r for r in pool if not math.isnan(r.get("gap", float("nan")))]
        pool.sort(key=lambda r: r.get("gap", 0), reverse=True)

    return pool[0] if pool else None


def write_code_comparison(
    records: list[dict],
    out: Path,
    *,
    classify_fn: Callable[[dict], str],
    family_labels: dict[str, str],
) -> None:
    """Write a LaTeX lstlisting figure comparing an honest and a hacked program.

    Parameters
    ----------
    classify_fn:
        Maps a record to a taxonomy family ID.
    family_labels:
        Mapping from family ID to human-readable label.
    """
    honest_rec = select_example(records, early=True, honest=True, classify_fn=classify_fn)
    hacked_rec = select_example(records, early=False, honest=False, classify_fn=classify_fn)

    if not honest_rec or not hacked_rec:
        print(f"  WARN: could not find example pair, skipping {out.name}")
        return

    h_code = (honest_rec.get("code") or "").strip()
    x_code = (hacked_rec.get("code") or "").strip()
    h_gap = honest_rec.get("gap", 0)
    x_gap = hacked_rec.get("gap", 0)
    h_batch = honest_rec.get("batch", 0)
    x_batch = hacked_rec.get("batch", 0)
    x_cat = classify_fn(hacked_rec)
    x_label = family_labels.get(x_cat, x_cat)

    lst = (
        "language=Python, basicstyle=\\scriptsize\\ttfamily, "
        "breaklines=true, frame=single, xleftmargin=2pt, xrightmargin=2pt"
    )

    lines = [
        "% autogenerated by scripts/make_grpo_figures.py",
        "\\begin{figure*}[t]",
        "\\centering",
        "\\begin{minipage}[t]{0.48\\linewidth}",
        f"\\textbf{{(a) Honest model}} (batch~{h_batch}, gap~$=$~{h_gap:.1f})",
        f"\\begin{{lstlisting}}[{lst}]",
        h_code,
        "\\end{lstlisting}",
        "\\end{minipage}",
        "\\hfill",
        "\\begin{minipage}[t]{0.48\\linewidth}",
        f"\\textbf{{(b) {x_label}}} (batch~{x_batch}, gap~$=$~{x_gap:.1f})",
        f"\\begin{{lstlisting}}[{lst}]",
        x_code,
        "\\end{lstlisting}",
        "\\end{minipage}",
        "\\caption{Representative programs from GRPO training. "
        "The honest model~(a) defines a properly normalized "
        "distribution over the data (gap~$\\approx 0$). "
        f"The hacked model~(b), classified as \\emph{{{x_label}}}, "
        "manipulates the scorer's log-probability calculation to inflate "
        "the reported reward without improving data fit "
        f"(gap~$=$~{x_gap:.1f}).}}",
        "\\label{fig:code-comparison}",
        "\\end{figure*}",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {out.name}")
