from __future__ import annotations

import math
from pathlib import Path
from typing import Any


def fmt_pm_std(mean_: float, std_: float) -> str:
    if math.isnan(mean_) or math.isnan(std_):
        return "n/a"
    return f"{mean_:.3f} $\\pm$ {std_:.3f}"


def write_baseline_vs_trained_table(
    out_path: Path,
    *,
    baseline: dict[str, Any] | None,
    condition_rows: list[dict[str, Any]],
) -> None:
    lines: list[str] = []
    lines.append("% Autogenerated by scripts/make_paper_artifacts.py")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append(
        "Condition & Gap (final, reported - proxy) & Any exploit (final) & Valid gap rate \\\\"
    )
    lines.append("\\midrule")

    if baseline is not None:
        lines.append(
            "Baseline (untrained) "
            f"& {baseline.get('gap', float('nan')):.3f} "
            f"& {baseline.get('any_exploit_rate', float('nan')) * 100:.1f}\\% "
            f"& {baseline.get('gap_valid_rate', float('nan')) * 100:.1f}\\% \\\\"
        )
        lines.append("\\midrule")

    for row in condition_rows:
        lines.append(
            f"{row['label']} "
            f"& {row['gap_pm_std']} "
            f"& {row['any_exploit_pm_std']} "
            f"& {row['gap_valid_pm_std']} \\\\"
        )

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_normalization_table(
    out_path: Path,
    *,
    condition_rows: list[dict[str, Any]],
) -> None:
    lines: list[str] = []
    lines.append("% Autogenerated by scripts/make_paper_artifacts.py")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append("Condition & Non-normalized (\\%) & Mean log-mass & Taxonomy tagged (\\%) \\\\")
    lines.append("\\midrule")
    for row in condition_rows:
        lines.append(
            f"{row['label']} "
            f"& {row.get('normalization_frac_non_normalized_pm_std', 'n/a')} "
            f"& {row.get('normalization_mean_log_mass_pm_std', 'n/a')} "
            f"& {row.get('taxonomy_tagged_pm_std', 'n/a')} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_lh_evidence_table(
    out_path: Path,
    *,
    condition_rows: list[dict[str, Any]],
) -> None:
    lines: list[str] = []
    lines.append("% Autogenerated by scripts/make_paper_artifacts.py")
    lines.append("\\begin{tabular}{lrrrrrr}")
    lines.append("\\toprule")
    lines.append(
        "Condition & Non-normalized (\\%) & Mean log-mass & Mean $|$log-mass$|$ "
        "& Taxonomy tagged (\\%) & Safety accept (\\%) & Gap \\\\"
    )
    lines.append("\\midrule")
    for row in condition_rows:
        lines.append(
            f"{row['label']} "
            f"& {row.get('normalization_frac_non_normalized_pm_std', 'n/a')} "
            f"& {row.get('normalization_mean_log_mass_pm_std', 'n/a')} "
            f"& {row.get('normalization_mean_abs_log_mass_pm_std', 'n/a')} "
            f"& {row.get('taxonomy_tagged_pm_std', 'n/a')} "
            f"& {row.get('safety_acceptance_pm_std', 'n/a')} "
            f"& {row.get('gap_pm_std', 'n/a')} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
