"""Stan reward prompt pools for direct-Stan TRL training."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_SYSTEM_PROMPT_STAN = (
    "/no_think\n"
    "Write a Stan model for Bernoulli coin-flip data.\n"
    "Output ONLY one ```stan code block and no prose.\n\n"
    "Rules:\n"
    "- Use this exact data interface:\n"
    "  data { int<lower=1> N; array[N] int<lower=0, upper=1> y; }\n"
    "- Include `parameters` and `model` blocks.\n"
    "- Keep the model self-contained and syntactically valid Stan.\n"
    "- Do not include explanations outside the code block.\n"
)

_SYSTEM_PROMPT_STAN_LINEAR = (
    "Write a Stan regression model of X vs y.\n"
    "Output ONLY one ```stan code block and no prose.\n\n"
    "Use this exact Stan data interface:\n"
    "data {\n"
    "  int<lower=1> N;\n"
    "  vector[N] X;\n"
    "  vector[N] y;\n"
    "}\n\n"
    "Requirements:\n"
    "- Include `parameters` and `model` blocks.\n"
    "- The program must be self-contained and valid Stan.\n"
    "- You are allowed to use one real latent parameter however you like. Use this exact parameters interface:\n"
    "  parameters {\n"
    "    real beta;\n"
    "  }\n"
    "- Do not add extra data inputs or extra parameters.\n"
    "- Do not include explanations outside the code block.\n\n"
    "Example pattern (do not copy verbatim):\n"
    "```stan\n"
    "data {\n"
    "  int<lower=1> N;\n"
    "  vector[N] X;\n"
    "  vector[N] y;\n"
    "}\n"
    "parameters {\n"
    "  real beta;\n"
    "}\n"
    "model {\n"
    "  beta ~ normal(0, 1);\n"
    "  y ~ normal(beta * X, 1);\n"
    "}\n"
    "```\n"
)

_STAN_PROMPTS = [
    "Model coin flips with prior beliefs about bias.",
    "Infer the coin probability from observed flips.",
    "Estimate coin bias from observed flips.",
    "Fit a Bayesian Bernoulli model for 0/1 outcomes.",
    "Write a probabilistic model for binary coin-toss observations.",
    "Infer uncertainty over a latent coin-bias parameter.",
    "Create a Stan model for Bernoulli data with explicit priors.",
    "Model binary outcomes generated by repeated coin flips.",
    "Fit a coin-toss model and estimate posterior uncertainty.",
    "Construct a Bayesian coin-bias model from 0/1 data.",
]

_STAN_LINEAR_PROMPTS_PATH = Path(__file__).with_name("stan_linear_prompts.json")


@lru_cache(maxsize=1)
def _load_stan_linear_prompt_families() -> dict[str, list[str]]:
    with _STAN_LINEAR_PROMPTS_PATH.open(encoding="utf-8") as f:
        raw = json.load(f)
    if not isinstance(raw, dict):
        raise ValueError(f"{_STAN_LINEAR_PROMPTS_PATH} must contain a JSON object")

    families: dict[str, list[str]] = {}
    for raw_policy, raw_prompts in raw.items():
        policy = str(raw_policy).strip().lower()
        if policy != raw_policy:
            raise ValueError(f"Stan linear prompt policy key must be normalized: {raw_policy!r}")
        if not isinstance(raw_prompts, list) or not raw_prompts:
            raise ValueError(f"Stan linear prompt policy {policy!r} must be a non-empty list")
        prompts: list[str] = []
        for idx, prompt in enumerate(raw_prompts):
            if not isinstance(prompt, str) or not prompt.strip():
                raise ValueError(
                    f"Stan linear prompt policy {policy!r} has invalid prompt at index {idx}"
                )
            prompts.append(prompt)
        families[policy] = prompts
    return families


STAN_LINEAR_PROMPT_POLICIES = frozenset(_load_stan_linear_prompt_families())


def get_stan_prompts(n: int) -> list[str]:
    if n <= 0:
        return []
    return [_STAN_PROMPTS[i % len(_STAN_PROMPTS)] for i in range(n)]


def _validate_stan_linear_prompt_policy(prompt_policy: str) -> str:
    policy = str(prompt_policy).strip().lower()
    if policy not in STAN_LINEAR_PROMPT_POLICIES:
        raise ValueError(
            "prompt_policy must be one of "
            f"{sorted(STAN_LINEAR_PROMPT_POLICIES)}"
        )
    return policy


def get_stan_linear_prompt_count(*, prompt_policy: str = "neutral_family") -> int:
    policy = _validate_stan_linear_prompt_policy(prompt_policy)
    return len(_load_stan_linear_prompt_families()[policy])


def get_stan_linear_prompts(
    n: int,
    *,
    prompt_policy: str = "neutral_family",
) -> list[str]:
    if n <= 0:
        return []
    policy = _validate_stan_linear_prompt_policy(prompt_policy)
    source = _load_stan_linear_prompt_families()[policy]
    if n > len(source):
        raise ValueError(
            f"n_prompts={n} exceeds the {len(source)} available Stan linear prompts "
            f"for prompt_policy={policy!r}"
        )
    return list(source[:n])


def _apply_thinking_mode(system_prompt: str, *, thinking_mode: str) -> str:
    mode = str(thinking_mode).strip().lower()
    if mode not in {"think", "no_think"}:
        raise ValueError("thinking_mode must be think|no_think")
    if mode == "no_think":
        return "/no_think\n" + system_prompt
    return system_prompt


def load_stan_reward_prompts(
    *,
    max_examples: int | None = None,
) -> list[dict[str, list[dict[str, str]]]]:
    prompt_count = 20 if max_examples is None else max_examples
    prompts = get_stan_prompts(prompt_count)
    return [
        {
            "prompt": [
                {"role": "system", "content": _SYSTEM_PROMPT_STAN},
                {"role": "user", "content": p},
            ]
        }
        for p in prompts
    ]


def load_stan_linear_reward_prompts(
    *,
    max_examples: int | None = None,
    thinking_mode: str = "no_think",
    prompt_policy: str = "neutral_family",
) -> list[dict[str, list[dict[str, str]]]]:
    prompt_count = 20 if max_examples is None else max_examples
    prompts = get_stan_linear_prompts(prompt_count, prompt_policy=prompt_policy)
    system_prompt = _apply_thinking_mode(
        _SYSTEM_PROMPT_STAN_LINEAR,
        thinking_mode=thinking_mode,
    )
    return [
        {
            "prompt": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": p},
            ]
        }
        for p in prompts
    ]
