# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

launcher:
  kind: slurm-h100

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 720
    cpus_per_task: 16
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 128
    nodes: 1
    partition: h100
    array_parallelism: 8

